[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = [
	{ name = "clean", path = "web/Makefile.toml" },
]

[tasks.debug]
dependencies = [
	"build-debug",
	"bundle-debug",
]

[tasks.release]
dependencies = [
	"build-release",
	"bundle-release",
]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = [
	{ name = "test", path = "web/Makefile.toml" }
]

[tasks.build-debug]
command = "cargo"
args = ["build"]
dependencies = [
	{ name = "debug", path = "web/Makefile.toml" },
]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
dependencies = [
	{ name = "release", path = "web/Makefile.toml" },
]

[tasks.bundle]
script_runner = "@shell"
script = '''
rm -rF dist
mkdir dist
cp -r target/admin dist # shell2batch: xcopy target\admin dist\admin /e /i
cp config.toml dist
'''

[tasks.bundle-debug]
script_runner = "@shell"
script = 'cp target/debug/vtt-server.exe dist'
dependencies = [
	"bundle",
]

[tasks.bundle-release]
script_runner = "@shell"
script = 'cp target/release/vtt-server.exe dist'
dependencies = [
	"bundle",
]
