[tasks.debug]
dependencies = [
	"build-debug",
	"bundle-debug",
]

[tasks.release]
dependencies = [
	"build-release",
	"bundle-release",
]

[tasks.build-debug]
command = "cargo"
args = ["build"]
dependencies = [
	{ name = "trunk-debug", path = "web/Makefile.toml" },
]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
dependencies = [
	{ name = "trunk-release", path = "web/Makefile.toml" },
]

[tasks.bundle]
script_runner = "@shell"
script = '''
rm -rF dist
mkdir dist
cp -r target/web dist # shell2batch: xcopy target\web dist\web /e /i
'''

[tasks.bundle-debug]
script_runner = "@shell"
script = '''
cp target/debug/vtt-server.exe dist
'''
dependencies = [
	"bundle",
]

[tasks.bundle-release]
script_runner = "@shell"
script = '''
cp target/release/vtt-server.exe dist
'''
dependencies = [
	"bundle",
]
