[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.debug]
dependencies = [
	"npm-install",
	"stylus",
	"trunk-debug",
]

[tasks.release]
dependencies = [
	"npm-install",
	"stylus",
	"trunk-release",
]

[tasks.npm-install]
script_runner = "@shell"
script = 'npm install'

[tasks.stylus]
script_runner = "@shell"
script = 'npm run stylus'

[tasks.trunk-debug]
script_runner = "@shell"
script = 'trunk build'

[tasks.trunk-release]
script_runner = "@shell"
script = 'trunk build --release'
